[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gvms"
version = "1.0.0"
dynamic = ["description", "readme", "requires-python", "license", "authors", "dependencies"]
